[features]
seeds = true
skip-lint = false
[programs.localnet]
crunchy_vs_smooth = "Fo9d34XdUczXdNt9jkqrQseyUQys9bmTDC31utY3zt5x"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/dagli/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
